language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build
  - cargo test

matrix:
  include:
  - rust: nightly
    env: CLIPPY=YESPLEASE
    script:
    - cargo rustc --lib --features "lint" -- -Zno-trans
