language: rust

rust:
  - stable
  - beta
  - nightly
sudo: true
dist: trusty
cache: cargo

before_install:
# openssl dependencies
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y pkg-config
  - sudo apt-get install -y openssl
# diesel dependencies
  - sudo apt-get install libpq-dev

before_script:
  #- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - which rustfmt || cargo install rustfmt
  - which diesel || cargo install diesel_cli --no-default-features --features postgres
  - which cargo-update || cargo install cargo-update
  - export PATH="$PATH:$HOME/.cargo/bin"
  - cargo install-update -a
  - diesel database setup

script:
  - cargo build
  - cargo test
  
after_success:
  #- travis-cargo coveralls --no-sudo

addons:
  postgresql: "9.5"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

matrix:
  allow_failures:
      - env: CLIPPY=YESPLEASE
  include:
    - rust: nightly
      env: CLIPPY=YESPLEASE
      script:
        - cargo fmt -- --write-mode=diff
        - cargo build --features "clippy"

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test

notifications:
  email:
    on_success: never
  