language: rust

rust:
  - stable
  - beta
  - nightly
sudo: true
dist: trusty

cache:
    cargo: true
    directories:
    - $HOME/openssl

install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - cargo install diesel_cli --debug --no-default-features --features postgres
  - export PATH=$HOME/.cargo/bin:$PATH
  - sudo apt-get install make
  - sudo apt-get install gcc
  - sudo apt-get install libssl-dev
  - sudo apt-get install pkg-config
  - cd
  - if [ ! -d "openssl" ]; then
      sudo apt-get remove openssl;
      git clone git://git.openssl.org/openssl.git ;
      cd openssl;
      ./config;
      make;
      sudo make install;
      sudo apt-get autoremove;
      openssl version;
      cd $TRAVIS_BUILD_DIR/;
    fi

before_script:
  #- diesel database setup

script:
  - cargo build
  - cargo test
  
after_success:
  - travis-cargo coveralls --no-sudo

addons:
  postgresql: "9.5"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

matrix:
  include:
    - rust: nightly
      env: CLIPPY=YESPLEASE
      install:
        - cargo install --force clippy
      script:
        - cargo clippy

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test

notifications:
  email:
    on_success: never
  