[package]
name = "homepage"
version = "0.5.7"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
readme = "README.md"
homepage = "jnferner.com"
repository = "git@github.com:SirRade/homepage.git"
license = "AGPL-3.0"

[dependencies]
iron = "*"
mime = "*"
router = "*"
mount = "*"
staticfile = "*"
diesel = "*"
postgres = "*"
handlebars-iron = "*"
handlebars = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

[features]
default = ["handlebars-iron/unstable"]

[badges]
travis-ci = { repository = "https://travis-ci.org/SirRade/chat.rs" }

[package.metadata.release]
sign-commit = true
upload-doc = true
