[package]
name = "homepage"
version = "0.5.8"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
readme = "README.md"
homepage = "jnferner.com"
repository = "git@github.com:SirRade/homepage.git"
license = "AGPL-3.0"

[dependencies]
iron = "*"
mime = "*"
router = "*"
mount = "*"
staticfile = "*"
diesel = "*"
postgres = "*"
handlebars-iron = { version = "*", features = ["unstable"] }
handlebars = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
redis = "*"
iron-sessionstorage = { version = "*", features = ["redis-backend"] }
clippy = {version = "*", optional = true}

[features]
default = []

[badges]
travis-ci = { repository = "https://travis-ci.org/SirRade/chat.rs" }

[package.metadata.release]
sign-commit = true
upload-doc = true
