[package]
name = "chat"
version = "0.4.3"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]

[dependencies]
iron = "*"
mime = "*"
router = "*"
diesel = "*"
postgres = "*"
handlebars-iron = "*"
serde = "*"
serde_json = "*"

